### ISSUE TITLE
some changes at doodle.com

### ISSUE THREAD

**Issue by michabbb** [xperseguers/doodle_client#9]
hi, do you cover the latest changes at doodle ? they changed a lot and i noticed, that some stuff isn´t working anymore.... ;(

**Comment by xperseguers** [comment]
Hi, no did not pay attention since what I use just seems to still work. Would you mind elaborate a bit and describe what is this "some stuff" not working anymore?

**Comment by michabbb** [comment]
I will check in detail, I wanted to ask you first 🤔

**Comment by michabbb** [comment]
@xperseguers problem is: when calling http://doodle.com/poll/xxxxxxxxx you get now a redirect to the new beta website... and i didn´t find out, howto block this redirect.... maybe with some cookie data, i don´t know.
as a web user you are able to switch between beta and old website, but i cannot find the trigger, that makes this switch permanent ;-( would be happy if you could take a look into this.
i was able to see a difference in the cookie, there exists a key called `d-forceBeta` which isn´t there when you are on the old website, but its there, when you are on the beta: `d-forceBeta: true` - i guess the framework here calls the beta stuff all the time, but when it comes to reading *participants* - the new website code no longer works... it would work, if we would stay on the old website ...... i debugged now a while, but i didn´t get it... would be very very happy if you could check this out... many thanks !!

**Comment by michabbb** [comment]
it looks like i got this fixed by [adding](https://github.com/michabbb/doodle_client/commit/805ff1162d17eb3ce5c0d60fb01e693fcd54bf6c) these keyvalues to the persistant cookie:

```php
$cookies['d-betaCode'] = $cookies['DoodleAuthentication'];
$cookies['d-betaCode']['name'] = 'd-betaCode';
$cookies['d-betaCode']['value'] = true;
$cookies['d-forceBeta'] = $cookies['DoodleAuthentication'];
$cookies['d-forceBeta']['name'] = 'd-forceBeta';
$cookies['d-forceBeta']['value'] = false;
```

**Comment by michabbb** [comment]
if someone is looking for a working version, please look here: https://github.com/michabbb/doodle_client

**Comment by NicoHood** [comment]
Hi,
I am also searching for a way to access doodle with scripts. I want to use python, so this library is no option for me. However it seems you are the only person who figured it out, how the API works.

Would you mind writing some short readme with an overview how the API works and what pitfalls you have to avoid?

If I had to do it on my own, my idea is to export the (existing) poll as XLS and parse the excel file. Some details on your site would be really helpful :)

Edit: I also found this in the readme: "I was surprised to find only a basic API to initiate polls (not actually creating them, just pre-filling the form)". I am also interested in this pre-filling. Can you tel me more about it?

**Comment by xperseguers** [comment]
Hi,

Well, there is no public API available so I reverse-engineered the website using the developer tools of my browser.

Basically the idea is to simulate what the browser does using your favourite programming language. I'm pretty sure you may understand how PHP works by reading if you know Python.

The "connection" is the central point. You find its definition here: https://github.com/xperseguers/doodle_client/blob/master/src/Client.php#L226

There are two calls, one to get an authentication "token" (line 234), this is where you POST your credentials, and another one to create the various cookies (line 242). The point here is that I ask PHP to behave just like a web browser and to store the various cookies automatically for me, and send them automatically as well when I do another request. If Python does not let you do that, you will have to parse the various response from the two calls I mentioned above to extract the cookie definitions and think about providing them as part of the other requests you will do to fetch/store data.

HTH

**Comment by NicoHood** [comment]
Hi,
I also played with my browser debug tools and it seems they do have a proper REST API. Did you try that?

Note: I am using doodle **without** an account. So no authentication nor cookies seem to be required. You need to pass the admin token in order to get the email address or do changes.

My findings so far:

Create new poll
POST https://doodle.com/api/v2.0/polls
```json
{
  "initiator": {
    "name": "test",
    "email": "test@test.de",
    "notify": true,
    "timeZone": "Etc/GMT+12"
  },
  "participants": [],
  "comments": [],
  "options": [
    {
      "text": "Zusage"
    },
    {
      "text": "Absage"
    }
  ],
  "title": "Test Poll",
  "type": "TEXT",
  "description": "",
  "preferencesType": "YESNO",
  "hidden": false,
  "askAddress": false,
  "askEmail": false,
  "askPhone": false,
  "locale": "en"
}
```

reply
```json
{
  "id": "removed",
  "adminKey": "removed",
  "latestChange": 1534364107139,
  "initiated": 1534364107139,
  "participantsCount": 0,
  "inviteesCount": 0,
  "type": "TEXT",
  "preferencesType": "YESNO",
  "state": "OPEN",
  "locale": "en",
  "title": "Test Poll",
  "initiator": {
    "name": "test",
    "email": "test@test.de",
    "notify": true
  },
  "options": [
    {
      "text": "Zusage",
      "available": true
    },
    {
      "text": "Absage",
      "available": true
    }
  ],
  "optionsHash": "4c69675682c4570a13a56f511e654ddf",
  "participants": [],
  "invitees": [],
  "device": "WEB",
  "levels": "YESNO"
}
```

Response
```json
{
  "id": "removed",
  "adminKey": "removed",
  "latestChange": 1534354560154,
  "initiated": 1534354560154,
  "participantsCount": 0,
  "inviteesCount": 0,
  "type": "TEXT",
  "preferencesType": "YESNO",
  "state": "OPEN",
  "locale": "en",
  "title": "Test Poll",
  "initiator": {
    "name": "test",
    "email": "test@nicohood.de",
    "notify": true
  },
  "options": [
    {
      "text": "Zusage",
      "available": true
    },
    {
      "text": "Absage",
      "available": true
    }
  ],
  "optionsHash": "4c69675682c4570a13a56f511e654ddf",
  "participants": [],
  "invitees": [],
  "device": "WEB",
  "levels": "YESNO"
}
```

Retrieve poll data (more info with admin key)
GET https://doodle.com/api/v2.0/polls/{poll}?adminKey={key}&participantKey
```json
{
  "id": "removed",
  "adminKey": "removed",
  "latestChange": 1534353212655,
  "initiated": 1534318519284,
  "participantsCount": 1,
  "inviteesCount": 0,
  "type": "TEXT",
  "preferencesType": "YESNO",
  "state": "OPEN",
  "locale": "de_DE",
  "title": "test23lol",
  "initiator": {
    "name": "test",
    "email": "test@test.de",
    "notify": true
  },
  "options": [
    {
      "text": "a",
      "available": true
    },
    {
      "text": "b",
      "available": true
    }
  ],
  "optionsHash": "66b69f6e54562b52ab37ccecbea18e40",
  "comments": [
    {
      "id": 1442273704,
      "author": "test",
      "timestamp": 1534318571951,
      "text": "test"
    }
  ],
  "participants": [
    {
      "id": 51816332,
      "name": "testuser",
      "preferences": [
        1,
        0
      ]
    }
  ],
  "invitees": [],
  "device": "WEB",
  "levels": "YESNO"
}
```

Edit poll:
POST https://doodle.com/api/v2.0/polls/{poll}?notifyallinvitees=true&rtoken=null
Content-Type: application/json
```json
{
  "adminKey": "removed",
  "latestChange": 1534353212655,
  "initiated": 1534318519284,
  "participantsCount": 1,
  "inviteesCount": 0,
  "type": "TEXT",
  "preferencesType": "YESNO",
  "state": "OPEN",
  "locale": "en",
  "title": "test23lol",
  "optionsHash": "66b69f6e54562b52ab37ccecbea18e40",
  "device": "WEB",
  "description": "",
  "hidden": false,
  "askAddress": false,
  "askEmail": false,
  "askPhone": false,
  "initiator": {
    "name": "test",
    "email": "test@test.de",
    "notify": true,
    "timeZone": "Etc/GMT+12"
  },
  "id": "removed",
  "participants": [
    {
      "id": 51816332,
      "name": "testuser",
      "preferences": [
        1,
        0
      ]
    }
  ],
  "options": [
    {
      "text": "a",
      "available": true,
      "final": false
    },
    {
      "text": "b",
      "available": true,
      "final": false
    }
  ],
  "comments": [
    {
      "id": 1442273704,
      "author": "test",
      "timestamp": 1534318571951,
      "text": "test"
    },
    {
      "author": "",
      "text": ""
    }
  ]
}
```

participate
POST https://doodle.com/api/v2.0/polls/{poll}/participants?adminKey={key}
Content-Type: application/json
```json
{
  "name": "testuser",
  "preferences": [
    1,
    0
  ],
  "optionsHash": "4c69675682c4570a13a56f511e654ddf",
  "participantKey": null
}
```

add comment
POST https://doodle.com/api/v2.0/polls/{poll}/comments?adminKey={key}
Content-Type: application/json
```json
{
  "author": "testuser3",
  "text": "test",
  "timestamp": "2018-08-15T17:42:51.462Z"
}
```

Why not use this? It seems pretty straight forward to use.

**Comment by NicoHood** [comment]
But how can I pre-fill the form with some entires? I'd like to send users a link to the poll with their name pre-filled out.

**Comment by michabbb** [comment]
@NicoHood in my eyes this pre-fill stuff makes no sense, because users have to use an account so that nobody else can delete or change their entries. using doodle without a user account makes no sense for me so when someone gets the link, you should tell them, to use a doodle account, and when they do, the name and email is always there, because it´s part of the users account.

**Comment by NicoHood** [comment]
@michabbb For my usecase not everybody has a doodle account, or is on the device with the doodle account. So we need some kind of precise user recognition. Prefilling the form would help here.

I asked the doodle team, but they say such a feature does not exist, nor a proper API (which is a lie).

**Comment by michabbb** [comment]
Using Doodle without a user account will cause you trouble, everybody who knows the url, is able to modify all entries, you should really avoid that. Without a account you don't get any notifications, so again, that makes no sense at all.

**Comment by NicoHood** [comment]
You get an admin token, which allows you to change the poll properties. And you get notifications via email. Everyone can edit everyones choice, but thats not a problem in my case. I use it more for polls where people can select if they attend the party or not, so i have a better overview. And my friends also know who joins and who not. But thats just how I use doodle :)

**Comment by dalleria** [comment]
@nicohood how did you find the endpoints of doodle v2 API ? And the right templates ?

**Comment by NicoHood** [comment]
With the network analysis tools of the browser. On firefox hit f12 and go to network. Inspect the traffic for json packages. The rest is reverse engineering. But I never used the doodle api, I abandoned the project.

**Comment by dalleria** [comment]
Ok thank you, everything is displayed
